### PR TITLE
Dimmer Switch

### PR DESCRIPTION
**Pull request by MichaelCWarren**
Not sure if this is something you would want, but I figured I'd at least create a PR just in case.

### CODE REVIEW

**Comment by ZeliardM** [comment]
No, this is great. I've been working on it, just don't have devices to test. I will look at this from my end and probably push it to a beta first. Thanks so much for the hard work!

**Comment by ZeliardM** [comment]
@MichaelCWarren I have been digging into this and this will be a quick fix just the dimmer switches. There are newer HS240 Model switches that are dual dimmer/fan controls which I would also like to support as well. I will most likely close this after I implement the rest of the changes I have going on, but the initial work was greatly appreciated.

**Comment by MichaelCWarren** [comment]
Good deal.

**Comment by ZeliardM** [comment]
@MichaelCWarren I have published a beta, v2.7.0-beta.1 that should have the initial workings for lighting and dimmer switches. Can you give it a shot and let me know how it goes? I will close out this PR and if you can, open an issue for dealing with any problems for lighting and dimmers with the beta? Thanks!

**Pull request closed without merging**
