### PR TITLE
V2.7.0 beta

### LINKED ISSUE #13: Errors with v2.7.0-beta.2
I'm getting this when running with the latest beta 2.7.0-beta.2.

```
Traceback (most recent call last):

  File "<string>", line 32, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__

ValueError: Argument for kasa.credentials.Credentials.__mashumaro_from_dict__ method should be a dict instance


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py", line 370, in <module>
    uvicorn.run(app, host="0.0.0.0", port=port, loop="asyncio")
    │       │   │                         └ 34573
    │       │   └ <Quart 'kasaApi'>
    │       └ <function run at 0x7f80c3d6cae0>
    └ <module 'uvicorn' from '/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/uvicorn/__init__.py'>

  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x7f80c3d6f740>
    └ <uvicorn.server.Server object at 0x7f80c39213d0>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f80c3d6f7e0>
           │       │   └ <uvicorn.server.Server object at 0x7f80c39213d0>
           │       └ <function run at 0x7f80c4ab8680>
           └ <module 'asyncio' from '/usr/lib/python3.12/asyncio/__init__.py'>
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7f80c1fab760>
           │      └ <function Runner.run at 0x7f80c3ec3100>
           └ <asyncio.runners.Runner object at 0x7f80c250c530>
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-6' coro=<Server.serve() running at /var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-package...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7f80c3ec0d60>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7f80c250c530>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f80c3ec0cc0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f80c3ec2ac0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1987, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f80c4014fe0>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f80c05b68f0>()>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/asgi.py", line 98, in handle_request
    response = await self.app.handle_request(request)
                     │    │   │              └ <Request 'http://127.0.0.1:34573/getSysInfo' [POST]>
                     │    │   └ <function Quart.handle_request at 0x7f80c1fe85e0>
                     │    └ <Quart 'kasaApi'>
                     └ <quart.asgi.ASGIHTTPConnection object at 0x7f80c05b5df0>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/app.py", line 1404, in handle_request
    return await self.full_dispatch_request(request_context)
                 │    │                     └ <quart.ctx.RequestContext object at 0x7f80c05b7800>
                 │    └ <function Quart.full_dispatch_request at 0x7f80c1fe8720>
                 └ <Quart 'kasaApi'>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/app.py", line 1440, in full_dispatch_request
    result = await self.dispatch_request(request_context)
                   │    │                └ <quart.ctx.RequestContext object at 0x7f80c05b7800>
                   │    └ <function Quart.dispatch_request at 0x7f80c1fe8a40>
                   └ <Quart 'kasaApi'>
  File "/var/lib/homebridge/kasa-python/.venv/lib/python3.12/site-packages/quart/app.py", line 1536, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
                 │    │            │          │        └ {}
                 │    │            │          └ <Request 'http://127.0.0.1:34573/getSysInfo' [POST]>
                 │    │            └ <function get_sys_info_route at 0x7f80c1feaca0>
                 │    └ <function Quart.ensure_async at 0x7f80c1fdbce0>
                 └ <Quart 'kasaApi'>

> File "/homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py", line 336, in get_sys_info_route
    sys_info = await get_sys_info(device_config)
                     │            └ {'connection_type': {'device_family': 'IOT.SMARTPLUGSWITCH', 'encryption_type': 'XOR', 'https': False}, 'credentials': Creden...
                     └ <function get_sys_info at 0x7f80c1fea840>

  File "/homebridge/node_modules/homebridge-kasa-python/dist/python/kasaApi.py", line 242, in get_sys_info
    dev = await Device.connect(config=Device.Config.from_dict(device_config))
                │      │              │      │      │         └ {'connection_type': {'device_family': 'IOT.SMARTPLUGSWITCH', 'encryption_type': 'XOR', 'https': False}, 'credentials': Creden...
                │      │              │      │      └ <classmethod(<function __mashumaro_from_dict__ at 0x7f80c34a5b20>)>
                │      │              │      └ <class 'kasa.deviceconfig.DeviceConfig'>
                │      │              └ <class 'kasa.device.Device'>
                │      └ <staticmethod(<function Device.connect at 0x7f80c2a0b9c0>)>
                └ <class 'kasa.device.Device'>

  File "<string>", line 34, in __mashumaro_from_dict__

mashumaro.exceptions.InvalidFieldValue: Field "credentials" of type Optional[Credentials] in DeviceConfig has invalid value Credentials()
[12/6/2024, 7:07:19 PM] [KasaPython] 2024-12-06 19:07:19.264 | ERROR    | __main__:get_sys_info_route:339 - Error getting system info: Field "credentials" of type Optional[Credentials] in DeviceConfig has invalid value Credentials()
```

Also, I discovered (before you updated), that it is seeing my dimmer switches as a bulb and trying to get the color_temp resulting in the following error (I think from the kasa-python) library.

`
[12/6/2024, 6:02:14 PM] [KasaPython] 2024-12-06 18:02:14.380 | DEBUG    | __main__:custom_sysinfo_config_serializer:44 - Serializing device: 192.168.4.62
[12/6/2024, 6:02:14 PM] [KasaPython] 2024-12-06 18:02:14.382 | ERROR    | __main__:create_device_info:212 - Error creating device info for 192.168.4.62: Bulb does not support colortemp.
`

### PR DESCRIPTION
**Pull request by MichaelCWarren**
Updated supported devices

### CODE REVIEW

**Comment by ZeliardM** [comment]
@MichaelCWarren The devices listed are not officially supported by the python-kasa library.

If you have the ability to set up a test environment and get the information needed below, I can set up a PR with the python-kasa developer and get them added.

All I need is the fixture files as described in the documentation linked below:

https://python-kasa.readthedocs.io/en/stable/contribute.html

If you added the models manually and the devices are working for you, then that should be all we need.

**Comment by MichaelCWarren** [comment]
Interesting.  They seem to be working fine for me.

I’ll see if I can get that for you.

- Michael

On Dec 7, 2024, at 4:14 PM, ZeliardM ***@***.***> wrote:

﻿

@MichaelCWarren<https://github.com/MichaelCWarren> The devices listed are not officially supported by the python-kasa library.

If you have the ability to set up a test environment and get the information needed below, I can set up a PR with the python-kasa developer and get them added.

All I need is the fixture files as described in the documentation linked below:

https://python-kasa.readthedocs.io/en/stable/contribute.html

If you added the models manually and the devices are working for you, then that should be all we need.

**Comment by ZeliardM** [comment]
@MichaelCWarren Excellent, yea, they are pretty quick about adding new devices that are confirmed working, so it would be officially in the next release, but I could update my plug-in to support them beforehand. Thanks for the information!

**Comment by MichaelCWarren** [comment]
fixtures/smart
[P115(US)_1.0_1.1.3.json](https://github.com/user-attachments/files/18052905/P115.US._1.0_1.1.3.json)

fixtures/iot
[KS200(US)_1.0_1.0.8.json](https://github.com/user-attachments/files/18052906/KS200.US._1.0_1.0.8.json)

**Comment by ZeliardM** [comment]
Thanks, I've submitted the official PR to the developers:
https://github.com/python-kasa/python-kasa/pull/1355
Once approved, it will be official, but I have added the models requested to v2.7.0-beta.4

**Pull request closed without merging**
